# Generated by Django 4.2 on 2026-06-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True, max_length=500, unique=True)),
                ("source_url", models.URLField(max_length=2000)),
                ("price", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("bedrooms", models.CharField(blank=True, max_length=20)),
                ("bathrooms", models.CharField(blank=True, max_length=20)),
                ("floor_size", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=500)),
                ("property_type", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
