# Generated by Django 4.2 on 2026-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
