# Generated by Django 4.2 on 2026-06-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post_raw_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="downloaded_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="post",
            name="image_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
