# Generated by Django 4.2 on 2026-06-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_post_downloaded_images_post_image_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScraperPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("title_sel", models.CharField(blank=True, max_length=500)),
                ("price_sel", models.CharField(blank=True, max_length=500)),
                ("desc_sel", models.CharField(blank=True, max_length=500)),
                ("location_sel", models.CharField(blank=True, max_length=500)),
                ("image_sel", models.CharField(blank=True, max_length=500)),
                ("confidence", models.FloatField(default=0.0)),
                ("source", models.CharField(default="auto", max_length=20)),
                ("scrape_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
