# Generated by Django 4.2 on 2026-06-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_scraperpattern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scraperpattern",
            name="source",
        ),
    ]
