# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from server import zcraper_pb2 as zcraper__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zcraper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Scrape = channel.unary_unary(
                '/zcraper.ZScraperService/Scrape',
                request_serializer=zcraper__pb2.ZScrapeRequest.SerializeToString,
                response_deserializer=zcraper__pb2.ZScrapeResponse.FromString,
                _registered_method=True)
        self.StreamImageURLs = channel.unary_stream(
                '/zcraper.ZScraperService/StreamImageURLs',
                request_serializer=zcraper__pb2.ZScrapeRequest.SerializeToString,
                response_deserializer=zcraper__pb2.ImageURL.FromString,
                _registered_method=True)


class ZScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Scrape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamImageURLs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Scrape': grpc.unary_unary_rpc_method_handler(
                    servicer.Scrape,
                    request_deserializer=zcraper__pb2.ZScrapeRequest.FromString,
                    response_serializer=zcraper__pb2.ZScrapeResponse.SerializeToString,
            ),
            'StreamImageURLs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamImageURLs,
                    request_deserializer=zcraper__pb2.ZScrapeRequest.FromString,
                    response_serializer=zcraper__pb2.ImageURL.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zcraper.ZScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zcraper.ZScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ZScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Scrape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zcraper.ZScraperService/Scrape',
            zcraper__pb2.ZScrapeRequest.SerializeToString,
            zcraper__pb2.ZScrapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamImageURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/zcraper.ZScraperService/StreamImageURLs',
            zcraper__pb2.ZScrapeRequest.SerializeToString,
            zcraper__pb2.ImageURL.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
